// File: src/pages/Reports.jsx (FINAL - DATA-DRIVEN)

import React, { useState } from 'react';
import { FileText, Download, Filter, Calendar, AlertCircle, CheckCircle, Clock, ChevronDown, X, Loader2, Plus } from 'lucide-react';

// --- IMPORT HOOK DATA UTAMA ---
import { useMachineData } from '../hooks/useMachineData';

// --- KOMPONEN KARTU KPI ---
const KpiCard = ({ title, value, icon: Icon, color, trend }) => (
  <div className="bg-dark-800 p-5 rounded-xl border border-dark-700 flex items-center justify-between">
    <div>
      <p className="text-gray-400 text-xs uppercase font-bold mb-1">{title}</p>
      <h3 className="text-2xl font-bold text-white">{value}</h3>
      <p className={`text-xs mt-1 ${trend && trend.includes('+') ? 'text-accent-success' : 'text-gray-500'}`}>
        {trend}
      </p>
    </div>
    <div className={`p-3 rounded-lg bg-dark-900 ${color}`}>
      <Icon size={20} />
    </div>
  </div>
);

const Reports = () => {
  // --- MENGAMBIL DATA DARI HOOK ---
  const { data, loading, error, refreshData } = useMachineData();

  // Safety check: ensure data structure exists
  const allTickets = data?.tickets || [];
  const dashboardStats = data?.stats || {};

  // --- STATES FRONTEND (Non-Backend Data) ---
  const [isDateDropdownOpen, setIsDateDropdownOpen] = useState(false);
  const [selectedRange, setSelectedRange] = useState('Last 30 Days');

  // State Modal Generate Report (Simulasi)
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [newReportTitle, setNewReportTitle] = useState('');

  // --- LOGIC PERHITUNGAN KPI DARI BACKEND DATA ---
  const totalReports = allTickets.length;
  // Fallback to filtering if high_risk_count is missing from stats
  const criticalIssuesCount = dashboardStats.high_risk_count ?? allTickets.filter(t => t.risk_level === 'CRITICAL').length;

  // Menghitung status (Pending Review adalah tiket yang dibuat hari ini)
  const pendingReviewCount = allTickets.filter(t =>
    new Date(t.timestamp).toDateString() === new Date().toDateString()
  ).length;

  // Rata-rata RUL diubah ke hari untuk KPI (dengan null safety)
  const avgRULDays = dashboardStats.avg_rul_all_tickets
    ? (dashboardStats.avg_rul_all_tickets / 24).toFixed(1)
    : '0.0';

  // --- LOGIC DOWNLOAD (FILE GENERATION) ---
  const handleDownload = (report) => {
    // Content for the text file
    const fileContent = `
      PREDICTIVE MAINTENANCE REPORT
      ---------------------------------------
      TICKET ID   : ${report.id || 'N/A'}
      DATE        : ${new Date(report.timestamp).toLocaleString()}
      MACHINE ID  : ${report.machine_id}
      ---------------------------------------
      RISK LEVEL  : ${report.risk_level}
      FAILURE TYPE: ${report.failure_type}
      PREDICTED RUL: ${(report.predicted_rul ?? 0).toFixed(1)} Hours
      
      AI ANALYSIS / RECOMMENDATION:
      ${report.ai_analysis || report.recommendation || "No detailed analysis provided."}
      
      ---------------------------------------
      Generated by Predictive Maintenance Copilot System
    `;

    // Create Blob and Trigger Download
    const blob = new Blob([fileContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Report_${report.machine_id}_Ticket${report.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // --- LOGIC GENERATE REPORT (Simulasi) ---
  const handleGenerate = () => {
    if (!newReportTitle) return alert("Judul laporan wajib diisi!");
    setIsGenerating(true);

    setTimeout(() => {
      // NOTE: Laporan yang di-generate user TIDAK disimpan di database (hanya simulasi frontend)
      setIsGenerating(false);
      setIsModalOpen(false);
      setNewReportTitle('');
      alert("✅ Laporan berhasil dibuat (simulasi)!");
    }, 1500);
  };

  // --- LOADING / ERROR STATES ---
  if (loading && !dashboardStats) {
    return (
      <div className="flex justify-center items-center h-full text-white text-lg">
        <Loader2 className="animate-spin mr-2" /> Loading Reports Data...
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8 bg-red-900/20 text-red-400 border border-red-700 rounded-xl">
        <h1 className="text-xl font-bold mb-2">Error Loading Data</h1>
        <p>Gagal mengambil data laporan dari backend API: {error.message || error}</p>
        <button onClick={refreshData} className="mt-4 px-4 py-2 bg-red-700 hover:bg-red-800 rounded-lg text-white font-bold">Try Again</button>
      </div>
    );
  }

  // --- RENDER UTAMA ---
  return (
    <div className="space-y-6 pb-10 relative">
      {/* HEADER */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">System Reports</h1>
          <p className="text-gray-400 text-sm">Generated insights & logs repository</p>
        </div>

        <div className="flex gap-3 relative">
          {/* DROPDOWN TANGGAL */}
          <div className="relative">
            <button
              onClick={() => setIsDateDropdownOpen(!isDateDropdownOpen)}
              className="flex items-center gap-2 px-4 py-2 bg-dark-800 hover:bg-dark-700 text-white text-sm rounded-lg border border-dark-700 transition"
            >
              <Calendar size={16} /> {selectedRange} <ChevronDown size={14} />
            </button>

            {isDateDropdownOpen && (
              <div className="absolute top-full right-0 mt-2 w-40 bg-dark-800 border border-dark-600 rounded-lg shadow-xl z-20 overflow-hidden">
                {['Last 7 Days', 'Last 30 Days', 'Last 3 Months', 'Year to Date'].map((range) => (
                  <button
                    key={range}
                    onClick={() => { setSelectedRange(range); setIsDateDropdownOpen(false); }}
                    className="block w-full text-left px-4 py-2 text-sm text-gray-300 hover:bg-dark-700 hover:text-white transition"
                  >
                    {range}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* TOMBOL NEW REPORT */}
          <button
            onClick={() => setIsModalOpen(true)}
            className="flex items-center gap-2 px-4 py-2 bg-accent-cyan text-dark-900 font-bold text-sm rounded-lg hover:bg-cyan-400 transition shadow-neon-cyan active:scale-95"
          >
            <Plus size={16} /> Generate New Report
          </button>
        </div>
      </div>

      {/* KPI STATISTICS */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <KpiCard title="Total Tickets" value={totalReports} icon={FileText} color="text-white" trend="Last 30 Days" />
        <KpiCard title="Critical Issues" value={criticalIssuesCount} icon={AlertCircle} color="text-accent-danger" trend="Current Active" />
        <KpiCard title="Pending Review" value={pendingReviewCount} icon={Clock} color="text-accent-warning" trend="Tickets Today" />
        <KpiCard title="Avg RUL" value={`${avgRULDays} days`} icon={CheckCircle} color="text-accent-success" trend="Avg resolution time" />
      </div>

      {/* CHARTS SECTION PLACEHOLDER */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 bg-dark-800 p-6 rounded-xl border border-dark-700 flex flex-col items-center justify-center text-center">
          <h3 className="font-bold text-white mb-2 w-full text-left">Anomaly Trends Over Time</h3>
          <div className="h-48 w-full flex flex-col items-center justify-center text-gray-500 bg-dark-900/50 rounded-lg border border-dark-600 border-dashed">
            <AlertCircle className="mb-2 opacity-50" />
            <p>Grafik historis membutuhkan integrasi Time-Series Database.</p>
            <p className="text-xs mt-1">(Fitur ini dinonaktifkan di versi Demo)</p>
          </div>
        </div>

        <div className="bg-dark-800 p-6 rounded-xl border border-dark-700 flex flex-col items-center justify-center text-center">
          <h3 className="font-bold text-white mb-2 w-full text-left">System Health</h3>
          <div className="h-48 w-full flex flex-col items-center justify-center text-gray-500 bg-dark-900/50 rounded-lg border border-dark-600 border-dashed">
            <CheckCircle className="mb-2 opacity-50" />
            <p>Data distribusi downtime tidak tersedia.</p>
          </div>
        </div>
      </div>

      {/* TABEL LAPORAN (REAL DATA) */}
      <div className="bg-dark-800 rounded-xl border border-dark-700 overflow-hidden">
        <div className="p-5 border-b border-dark-700 flex justify-between items-center">
          <h3 className="font-bold text-white">Maintenance Tickets (Reports)</h3>
          <button className="text-gray-400 hover:text-white" title="Filter"><Filter size={18} /></button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left text-gray-300">
            <thead className="bg-dark-900/50 text-gray-400 uppercase text-xs">
              <tr>
                <th className="p-4">ID</th>
                <th className="p-4">Date</th>
                <th className="p-4">Machine / Issue</th>
                <th className="p-4">Risk Level</th>
                <th className="p-4">RUL</th>
                <th className="p-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-dark-700">
              {allTickets.length > 0 ? (
                // SORTING: Tampilkan tiket terbaru di atas
                [...allTickets]
                  .sort((a, b) => (b.id - a.id))
                  .map((rpt) => (
                    <tr key={rpt.id} className="hover:bg-dark-700/50 transition-colors">
                      <td className="p-4 font-mono text-white">#{rpt.id}</td>
                      <td className="p-4 text-xs text-gray-400">
                        {new Date().toLocaleString()}
                      </td>
                      <td className="p-4">
                        <div className="font-medium text-accent-cyan font-mono">{rpt.machine_id}</div>
                        <div className="text-xs text-gray-300">{rpt.failure_type}</div>
                      </td>
                      <td className="p-4">
                        <span className={`px-2 py-1 rounded text-xs font-bold ${rpt.risk_level === 'CRITICAL' ? 'bg-red-900/20 text-red-400' :
                          rpt.risk_level === 'WARNING' ? 'bg-yellow-900/20 text-yellow-400' :
                            'bg-green-900/20 text-green-400'
                          }`}>
                          {rpt.risk_level}
                        </span>
                      </td>
                      <td className="p-4">{rpt.predicted_rul ? `${rpt.predicted_rul.toFixed(0)}h` : '-'}</td>
                      <td className="p-4 text-right">
                        <button
                          onClick={() => handleDownload(rpt)}
                          className="p-2 rounded-lg text-accent-cyan hover:bg-dark-600 hover:text-white cursor-pointer transition"
                          title="Download Report"
                        >
                          <Download size={18} />
                        </button>
                      </td>
                    </tr>
                  ))
              ) : (
                <tr>
                  <td colSpan="6" className="p-8 text-center text-gray-500">
                    No maintenance tickets found in the database.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* MODAL FORM GENERATE REPORT */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-dark-800 border border-dark-600 w-full max-w-md rounded-2xl p-6 shadow-2xl animate-in fade-in zoom-in duration-200">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-xl font-bold text-white">Generate New Report</h2>
              <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-white">
                <X size={24} />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-xs text-gray-400 mb-1 uppercase">Report Title</label>
                <input
                  type="text"
                  placeholder="e.g. Sector B Weekly Analysis"
                  value={newReportTitle}
                  onChange={(e) => setNewReportTitle(e.target.value)}
                  className="w-full bg-dark-900 border border-dark-600 rounded-lg p-3 text-white focus:border-accent-cyan focus:outline-none"
                />
              </div>
              <div>
                <label className="block text-xs text-gray-400 mb-1 uppercase">Format</label>
                <div className="flex gap-4">
                  <label className="flex items-center gap-2 text-sm text-gray-300">
                    <input type="radio" name="format" defaultChecked className="accent-accent-cyan" /> Text File (.txt)
                  </label>
                  <label className="flex items-center gap-2 text-sm text-gray-500 cursor-not-allowed">
                    <input type="radio" name="format" disabled className="accent-accent-cyan" /> PDF (Pro)
                  </label>
                </div>
              </div>
            </div>

            <div className="flex gap-3 mt-8">
              <button onClick={() => setIsModalOpen(false)} className="flex-1 py-3 bg-dark-700 hover:bg-dark-600 text-white rounded-xl font-medium transition">Cancel</button>
              <button onClick={handleGenerate} disabled={isGenerating} className="flex-1 py-3 bg-accent-cyan hover:bg-cyan-400 text-black rounded-xl font-bold transition flex items-center justify-center gap-2">
                {isGenerating ? <><Loader2 size={18} className="animate-spin" /> Generating...</> : "Create Report"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Reports;