import React, { useState } from "react";
import {
  FileText,
  Download,
  Filter,
  Calendar,
  AlertCircle,
  CheckCircle,
  Clock,
  ChevronDown,
  X,
  Loader2,
  Plus,
  User,
  Bot,
  Search,
  Eye,
} from "lucide-react";
import toast, { Toaster } from "react-hot-toast";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable"; 

import { useMachineData } from "../hooks/useMachineData";

const REPORT_CONFIG = {
  companyName: "PT. PROTEUS GUARDIAN INDUSTRIES",
  department: "Maintenance & Reliability Department",
  address: "Jl. Industri Raya No. 12, Kawasan Industri Pulogadung, Jakarta",
  preparedBy: "Maintenance Supervisor",
  approvedBy: "Plant Manager",
};

const KpiCard = ({ title, value, icon: Icon, color, trend }) => (
  <div className="bg-dark-800 p-5 rounded-xl border border-dark-700 flex items-center justify-between hover:border-dark-600 transition-all duration-300 shadow-sm group">
    <div>
      <p className="text-gray-400 text-[10px] md:text-xs uppercase font-bold mb-1 tracking-wider group-hover:text-gray-300 transition-colors">
        {title}
      </p>
      <h3 className="text-2xl md:text-3xl font-bold text-white mb-1">
        {value}
      </h3>
      <p
        className={`text-[10px] md:text-xs font-medium ${
          trend && trend.includes("+") ? "text-accent-success" : "text-gray-500"
        }`}
      >
        {trend}
      </p>
    </div>
    <div className={`p-3 rounded-xl bg-dark-900 shadow-inner ${color}`}>
      <Icon size={20} />
    </div>
  </div>
);

const Reports = () => {
  const { data, loading, error, refreshData } = useMachineData();

  const allTickets = data?.tickets || [];
  const dashboardStats = data?.stats || {};

  // STATES
  const [isDateDropdownOpen, setIsDateDropdownOpen] = useState(false);
  const [selectedRange, setSelectedRange] = useState("Last 30 Days");
  const [searchQuery, setSearchQuery] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [newReportTitle, setNewReportTitle] = useState("");
  const [exportFormat, setExportFormat] = useState("pdf");

  // STATE BARU UNTUK PREVIEW
  const [previewUrl, setPreviewUrl] = useState(null);
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);

  // LOGIC KPI
  const totalReports = allTickets.length;
  const criticalIssuesCount =
    dashboardStats.high_risk_count ??
    allTickets.filter((t) => t.risk_level === "CRITICAL").length;
  const pendingReviewCount = allTickets.filter(
    (t) => new Date(t.timestamp).toDateString() === new Date().toDateString()
  ).length;
  const avgRULDays = dashboardStats.avg_rul_all_tickets
    ? (dashboardStats.avg_rul_all_tickets / 24).toFixed(1)
    : "0.0";

  // LOGIC FILTER
  const filteredTickets = allTickets.filter((ticket) => {
    const query = searchQuery.toLowerCase();
    return (
      ticket.id.toString().includes(query) ||
      ticket.machine_id.toLowerCase().includes(query) ||
      (ticket.failure_type || "").toLowerCase().includes(query) ||
      ticket.risk_level.toLowerCase().includes(query)
    );
  });

  const generateProfessionalPDF = () => {
    if (allTickets.length === 0) {
        toast.error("Tidak ada data.");
        return null;
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;

    // --- HELPER: HEADER KOP SURAT ---
    const drawHeader = (doc, pageNo) => {
      // Background Header
      doc.setFillColor(31, 41, 55); 
      doc.rect(0, 0, pageWidth, 40, "F");

      // Text Company (White)
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.text(REPORT_CONFIG.companyName, margin, 15);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(REPORT_CONFIG.department, margin, 22);
      doc.setTextColor(200, 200, 200);
      doc.text(REPORT_CONFIG.address, margin, 27);

      // Judul Laporan (Kanan Atas)
      doc.setTextColor(6, 182, 212); // Accent Cyan
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("MAINTENANCE REPORT", pageWidth - margin, 33, {
        align: "right",
      });

      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.text(
        `Date: ${new Date().toLocaleDateString()}`,
        pageWidth - margin,
        22,
        { align: "right" }
      );
      doc.text(
        `Ref: PRT-${new Date().getTime().toString().slice(-6)}`,
        pageWidth - margin,
        27,
        { align: "right" }
      );
    };

    // --- HELPER: FOOTER (Page Number) ---
    const drawFooter = (doc, pageNo, totalPages) => {
      const str = `Page ${pageNo} of ${totalPages}`;
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.text(str, pageWidth - margin, pageHeight - 10, { align: "right" });
      doc.text(`Generated by Proteus Guardian`, margin, pageHeight - 10);
    };

    // --- HALAMAN 1: TABEL RANGKUMAN (SUMMARY) ---
    drawHeader(doc, 1);

    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Executive Summary", margin, 50);

    // Persiapan Data Tabel
    const tableRows = allTickets.map((t) => [
      `#${t.id}`,
      t.machine_id,
      new Date(t.timestamp).toLocaleDateString(),
      t.failure_type || "-",
      t.risk_level,
      t.ai_analysis && t.ai_analysis.includes("Manual Report") ? "Human" : "AI",
      t.predicted_rul ? `${t.predicted_rul.toFixed(0)} h` : "-",
    ]);

    autoTable(doc, {
      startY: 55,
      head: [["ID", "Machine", "Date", "Issue", "Risk", "Gen. By", "RUL"]],
      body: tableRows,
      theme: "grid",
      headStyles: {
        fillColor: [31, 41, 55],
        textColor: [6, 182, 212],
        fontStyle: "bold",
      }, 
      styles: { fontSize: 9, cellPadding: 3 },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      didParseCell: function (data) {
        if (data.section === "body" && data.column.index === 4) {
          if (data.cell.raw === "CRITICAL")
            data.cell.styles.textColor = [220, 53, 69]; 
          else if (data.cell.raw === "WARNING")
            data.cell.styles.textColor = [255, 193, 7]; 
          else data.cell.styles.textColor = [40, 167, 69]; 
        }
      },
    });

    // --- HALAMAN DETAIL (Looping) ---
    doc.addPage();
    drawHeader(doc, 2);

    let yPos = 50;
    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Detailed Analysis & AI Recommendations", margin, yPos);
    yPos += 10;

    allTickets.forEach((ticket, i) => {
      if (yPos > pageHeight - 60) {
        doc.addPage();
        drawHeader(doc);
        yPos = 50;
      }

      // Container
      doc.setDrawColor(200);
      doc.setFillColor(250, 250, 250);
      doc.roundedRect(margin, yPos, pageWidth - margin * 2, 35, 3, 3, "FD");

      // Info
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0);
      doc.text(
        `Ticket #${ticket.id} - ${ticket.machine_id}`,
        margin + 5,
        yPos + 8
      );

      // Status Badge
      const riskColor =
        ticket.risk_level === "CRITICAL"
          ? [220, 53, 69]
          : ticket.risk_level === "WARNING"
          ? [255, 165, 0]
          : [40, 167, 69];
      doc.setFillColor(...riskColor);
      doc.roundedRect(pageWidth - margin - 30, yPos + 3, 25, 6, 2, 2, "F");
      doc.setTextColor(255);
      doc.setFontSize(8);
      doc.text(ticket.risk_level, pageWidth - margin - 17.5, yPos + 7, {
        align: "center",
      });

      // Content
      doc.setTextColor(80);
      doc.text(
        `Issue: ${ticket.failure_type || "Unknown"}`,
        margin + 5,
        yPos + 15
      );
      doc.text(
        `Date: ${new Date(ticket.timestamp).toLocaleString()}`,
        margin + 5,
        yPos + 20
      );
      doc.text(
        `RUL: ${
          ticket.predicted_rul
            ? ticket.predicted_rul.toFixed(1) + " Hours"
            : "-"
        }`,
        margin + 5,
        yPos + 25
      );

      // AI Analysis
      yPos += 40;
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0);
      doc.text("AI Analysis:", margin, yPos);
      yPos += 5;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(50);
      const analysis = ticket.ai_analysis || "No analysis data available.";
      const splitText = doc.splitTextToSize(analysis, pageWidth - margin * 2);
      doc.text(splitText, margin, yPos);

      yPos += splitText.length * 4 + 10; 
      doc.setDrawColor(230);
      doc.line(margin, yPos - 5, pageWidth - margin, yPos - 5); 
    });

    // --- TANDA TANGAN ---
    if (yPos > pageHeight - 60) {
      doc.addPage();
      drawHeader(doc);
      yPos = 50;
    }

    yPos += 20;
    doc.setFontSize(10);
    doc.setTextColor(0);
    doc.text("Approved By,", margin, yPos);
    doc.text("Prepared By,", pageWidth - margin - 40, yPos);

    yPos += 25;
    doc.line(margin, yPos, margin + 40, yPos); 
    doc.line(pageWidth - margin - 40, yPos, pageWidth - margin, yPos); 

    doc.text(`( ${REPORT_CONFIG.approvedBy} )`, margin, yPos + 5);
    doc.text(
      `( ${REPORT_CONFIG.preparedBy} )`,
      pageWidth - margin - 40,
      yPos + 5
    );

    // Page Numbers
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      drawFooter(doc, i, totalPages);
    }

    return doc;
  };

  // --- HANDLER DOWNLOAD ---
  const handleDownloadPDF = () => {
    const doc = generateProfessionalPDF(); 
    if(doc) {
        doc.save(`${newReportTitle.replace(/\s+/g, "_") || "Official_Report"}.pdf`);
    }
  };

  // --- HANDLER PREVIEW (FIXED NAME) ---
  const handlePreviewPDF = () => {
    if (allTickets.length === 0) return toast.error("Tidak ada data.");
    const doc = generateProfessionalPDF(); 

    if(doc) {
        const blob = doc.output("bloburl");
        setPreviewUrl(blob);
        setIsPreviewOpen(true); 
    }
  };

//  TXT
  const generateProfessionalTXT = () => {
    if (allTickets.length === 0) return toast.error("Tidak ada data.");

    const pad = (str, length) => (str + "").padEnd(length).slice(0, length);
    const line = (len) => "=".repeat(len);
    const subline = (len) => "-".repeat(len);

    let content = "";

    // HEADER
    content += `${line(80)}\n`;
    content += `  ${REPORT_CONFIG.companyName.padEnd(76)}\n`;
    content += `  ${REPORT_CONFIG.department.padEnd(76)}\n`;
    content += `${line(80)}\n`;
    content += `  REPORT TITLE  : ${newReportTitle || "Maintenance Report"}\n`;
    content += `  GENERATED ON  : ${new Date().toLocaleString()}\n`;
    content += `  TOTAL TICKETS : ${allTickets.length}\n`;
    content += `${line(80)}\n\n`;

    // TABLE
    content += `SUMMARY DATA:\n`;
    content += `+------+-----------------+----------------+------------+----------+-------+\n`;
    content += `| ID   | MACHINE ID      | FAILURE TYPE   | RISK LEVEL | GEN. BY  | RUL   |\n`;
    content += `+------+-----------------+----------------+------------+----------+-------+\n`;

    allTickets.forEach((t) => {
      const isManual = t.ai_analysis && t.ai_analysis.includes("Manual Report");
      content += `| ${pad("#" + t.id, 4)} | ${pad(t.machine_id, 15)} | ${pad(
        (t.failure_type || "-").substring(0, 14),
        14
      )} | ${pad(t.risk_level, 10)} | ${pad(
        isManual ? "Human" : "AI",
        8
      )} | ${pad(
        t.predicted_rul ? t.predicted_rul.toFixed(0) + "h" : "-",
        5
      )} |\n`;
    });
    content += `+------+-----------------+----------------+------------+----------+-------+\n\n`;

    // DETAILED
    content += `DETAILED ANALYSIS & RECOMMENDATIONS\n`;
    content += `${line(80)}\n`;

    allTickets.forEach((t, index) => {
      const failType = t.failure_type || "Unknown";
      content += `\n[TICKET #${t.id}] MACHINE: ${t.machine_id}\n`;
      content += `${subline(40)}\n`;
      content += `Timestamp : ${new Date(t.timestamp).toLocaleString()}\n`;
      content += `Issue     : ${failType}\n`;
      content += `Risk      : ${t.risk_level}\n`;
      content += `Analysis  :\n${(
        t.ai_analysis || "No analysis provided."
      ).replace(/\n/g, "\n            ")}\n`; 
      content += `${subline(80)}\n`;
    });

    // FOOTER
    content += `\n\n`;
    content += `  Approved By,                            Prepared By,\n\n\n\n`;
    content += `  ( ${REPORT_CONFIG.approvedBy} )            ( ${REPORT_CONFIG.preparedBy} )\n`;
    content += `${line(80)}\n`;
    content += `Generated by Proteus Guardian System\n`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${
      newReportTitle.replace(/\s+/g, "_") || "Official_Report"
    }.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadSingleTxt = (report) => {
    const content = `TICKET #${report.id} REPORT\n------------------\nMachine: ${report.machine_id}\n...`; 
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Ticket_${report.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // --- HANDLER GENERATE ---
  const handleGenerate = () => {
    if (!newReportTitle.trim())
      return toast.error("Judul laporan wajib diisi!");
    setIsGenerating(true);
    setTimeout(() => {
      try {
        if (exportFormat === "pdf") {
          handleDownloadPDF(); // Panggil fungsi download
        } else {
          generateProfessionalTXT(); 
        }
        setIsGenerating(false);
        setIsModalOpen(false);
        setNewReportTitle("");
        toast.success(
          `Laporan Resmi ${exportFormat.toUpperCase()} berhasil dibuat!`
        );
      } catch (err) {
        console.error(err);
        setIsGenerating(false);
        toast.error("Gagal membuat laporan.");
      }
    }, 1500);
  };

  if (loading && !dashboardStats)
    return (
      <div className="flex flex-col justify-center items-center h-[80vh] text-white">
        <Loader2 className="animate-spin text-accent-cyan" size={40} />
      </div>
    );
  if (error)
    return <div className="text-red-500 p-10">Error: {error.message}</div>;

  return (
    <div className="space-y-4 md:space-y-6 pb-20 md:pb-10 relative">
      <Toaster position="top-center" reverseOrder={false} />

      {/* HEADER PAGE */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-dark-800/50 md:bg-transparent p-4 md:p-0 rounded-xl md:rounded-none border border-dark-700 md:border-none">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-white tracking-tight">
            System Reports
          </h1>
          <p className="text-gray-400 text-xs md:text-sm mt-1">
            Generated insights & logs repository
          </p>
        </div>
        <div className="flex flex-wrap md:flex-nowrap gap-3 w-full md:w-auto relative">
          <button
            onClick={() => setIsModalOpen(true)}
            className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2.5 bg-accent-cyan text-black font-bold text-sm rounded-lg hover:bg-cyan-400 transition whitespace-nowrap"
          >
            <Plus size={18} />{" "}
            <span className="hidden sm:inline">Generate Official Report</span>
          </button>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4">
        <KpiCard
          title="Total Tickets"
          value={totalReports}
          icon={FileText}
          color="text-gray-200"
          trend="Last 30 Days"
        />
        <KpiCard
          title="Critical Issues"
          value={criticalIssuesCount}
          icon={AlertCircle}
          color="text-accent-danger"
          trend="Current Active"
        />
        <KpiCard
          title="Pending Review"
          value={pendingReviewCount}
          icon={Clock}
          color="text-accent-warning"
          trend="Tickets Today"
        />
        <KpiCard
          title="Avg RUL"
          value={`${avgRULDays}d`}
          icon={CheckCircle}
          color="text-accent-success"
          trend="Avg resolution time"
        />
      </div>

      {/* Tabel */}
      <div className="bg-dark-800 rounded-xl border border-dark-700 overflow-hidden shadow-lg flex flex-col h-full">
        {/* HEADER TABEL + SEARCH */}
        <div className="p-4 md:p-5 border-b border-dark-700 flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-dark-800/80 backdrop-blur-sm sticky top-0 z-10">
          <div className="flex items-center gap-2">
            <FileText size={18} className="text-accent-cyan" />
            <h3 className="font-bold text-white text-sm md:text-base">
              Maintenance Reports
            </h3>
          </div>
          <div className="relative w-full md:w-64">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Search size={16} className="text-gray-500" />
            </div>
            <input
              type="text"
              placeholder="Search ticket, machine..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-dark-900 border border-dark-600 rounded-lg py-2 pl-10 pr-4 text-sm text-gray-200 focus:outline-none focus:border-accent-cyan transition-colors placeholder-gray-600"
            />
          </div>
        </div>

        <div className="overflow-x-auto w-full">
          <table className="w-full text-sm text-left text-gray-300 min-w-[800px] md:min-w-full">
            <thead className="bg-dark-900/80 text-gray-400 uppercase text-[10px] md:text-xs tracking-wider font-semibold">
              <tr>
                <th className="p-4 whitespace-nowrap">Ticket ID</th>
                <th className="p-4 whitespace-nowrap">Date Generated</th>
                <th className="p-4 whitespace-nowrap">Machine / Issue</th>
                <th className="p-4 whitespace-nowrap">Generated By</th>
                <th className="p-4 whitespace-nowrap">Risk Level</th>
                <th className="p-4 whitespace-nowrap">RUL Prediction</th>
                <th className="p-4 whitespace-nowrap text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-dark-700">
              {filteredTickets.length > 0 ? (
                [...filteredTickets]
                  .sort((a, b) => b.id - a.id)
                  .map((rpt, index) => {
                    const isManual =
                      rpt.ai_analysis &&
                      rpt.ai_analysis.includes("Manual Report");
                    return (
                      <tr
                        key={rpt.id}
                        className="hover:bg-dark-700/40 transition-colors"
                      >
                        <td className="p-4 font-mono text-accent-cyan font-medium">
                          #{index + 1}
                        </td>
                        <td className="p-4 text-xs text-gray-400 whitespace-nowrap">
                          <div className="text-white text-[14px]">
                            {new Date(rpt.timestamp).toLocaleDateString()}
                          </div>
                          <div className="text-[12px] text-gray-200">
                            {new Date(rpt.timestamp).toLocaleTimeString()}
                          </div>
                        </td>
                        <td className="p-4">
                          <div className="font-medium text-white mb-0.5">
                            {rpt.machine_id}
                          </div>
                          <div className="text-base text-gray-400 truncate max-w-[150px]">
                            {rpt.failure_type}
                          </div>
                        </td>
                        <td className="p-4">
                          <span
                            className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[10px] md:text-xs font-bold border ${
                              isManual
                                ? "bg-blue-900/20 text-blue-400 border-blue-900/30"
                                : "bg-purple-900/20 text-purple-400 border-purple-900/30"
                            }`}
                          >
                            {isManual ? <User size={12} /> : <Bot size={12} />}
                            {isManual ? "Human" : "AI"}
                          </span>
                        </td>
                        <td className="p-4">
                          <span
                            className={`px-2.5 py-1 rounded-md text-[10px] md:text-xs font-bold inline-flex items-center gap-1.5 ${
                              rpt.risk_level === "CRITICAL"
                                ? "bg-red-900/20 text-red-400 border border-red-900/30"
                                : rpt.risk_level === "WARNING"
                                ? "bg-yellow-900/20 text-yellow-400 border border-yellow-900/30"
                                : "bg-green-900/20 text-green-400 border border-green-900/30"
                            }`}
                          >
                            <span
                              className={`w-1.5 h-1.5 rounded-full ${
                                rpt.risk_level === "CRITICAL"
                                  ? "bg-red-500"
                                  : rpt.risk_level === "WARNING"
                                  ? "bg-yellow-500"
                                  : "bg-green-500"
                              }`}
                            ></span>
                            {rpt.risk_level}
                          </span>
                        </td>
                        <td className="p-4 font-mono text-gray-300 text-base">
                          {rpt.predicted_rul
                            ? `${rpt.predicted_rul.toFixed(0)} h`
                            : "-"}
                        </td>
                        <td className="p-4 text-right">
                          <button
                            onClick={() => handleDownloadSingleTxt(rpt)}
                            className="p-2 rounded-lg text-gray-400 hover:text-accent-cyan hover:bg-dark-700 transition"
                            title="Download Single Txt"
                          >
                            <Download size={18} />
                          </button>
                        </td>
                      </tr>
                    );
                  })
              ) : (
                <tr>
                  <td colSpan="7" className="p-12 text-center text-gray-500">
                    <Search size={40} className="mb-2 opacity-20 mx-auto" />
                    {allTickets.length > 0
                      ? `No results found for "${searchQuery}"`
                      : "No maintenance tickets found."}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* MODAL FORM */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
          <div className="bg-dark-800 border border-dark-600 w-full md:w-[500px] max-w-full rounded-2xl p-6 shadow-2xl animate-in zoom-in-95 duration-200">
            <div className="flex justify-between items-center mb-6 border-b border-dark-700 pb-4">
              <h2 className="text-lg md:text-xl font-bold text-white flex items-center gap-2">
                <Plus className="text-accent-cyan" size={20} /> Generate
                Official Report
              </h2>
              <button
                onClick={() => setIsModalOpen(false)}
                className="text-gray-400 hover:text-white bg-dark-700 p-1.5 rounded-lg transition"
              >
                <X size={20} />
              </button>
            </div>
            <div className="space-y-5">
              <div>
                <label className="block text-xs text-gray-400 mb-1.5 uppercase font-bold tracking-wider">
                  Report Title (Filename)
                </label>
                <input
                  type="text"
                  placeholder="e.g. Monthly_Maintenance_Recap"
                  value={newReportTitle}
                  onChange={(e) => setNewReportTitle(e.target.value)}
                  className="w-full bg-dark-900 border border-dark-600 rounded-lg p-3 text-white focus:border-accent-cyan focus:ring-1 focus:ring-accent-cyan focus:outline-none text-sm transition-all"
                />
              </div>
              <div>
                <label className="block text-xs text-gray-400 mb-2 uppercase font-bold tracking-wider">
                  Export Format
                </label>
                <div className="flex gap-4">
                  <label
                    className={`flex items-center gap-2 text-sm cursor-pointer p-3 rounded-lg border flex-1 transition ${
                      exportFormat === "pdf"
                        ? "border-accent-cyan bg-accent-cyan/10 text-white"
                        : "border-dark-600 bg-dark-900/50 text-gray-400 hover:border-gray-500"
                    }`}
                  >
                    <input
                      type="radio"
                      name="format"
                      checked={exportFormat === "pdf"}
                      onChange={() => setExportFormat("pdf")}
                      className="accent-accent-cyan w-4 h-4"
                    />{" "}
                    <FileText size={16} /> PDF (Official)
                  </label>
                  <label
                    className={`flex items-center gap-2 text-sm cursor-pointer p-3 rounded-lg border flex-1 transition ${
                      exportFormat === "txt"
                        ? "border-accent-cyan bg-accent-cyan/10 text-white"
                        : "border-dark-600 bg-dark-900/50 text-gray-400 hover:border-gray-500"
                    }`}
                  >
                    <input
                      type="radio"
                      name="format"
                      checked={exportFormat === "txt"}
                      onChange={() => setExportFormat("txt")}
                      className="accent-accent-cyan w-4 h-4"
                    />{" "}
                    <FileText size={16} /> TXT (Raw Data)
                  </label>
                </div>
              </div>
            </div>
            <div className="flex gap-3 mt-8 pt-2">
              <button
                onClick={() => setIsModalOpen(false)}
                className="flex-1 py-3 bg-transparent border border-dark-600 hover:bg-dark-700 text-gray-300 rounded-xl font-medium transition"
              >
                Cancel
              </button>

              {/* TOMBOL PREVIEW (Hanya jika PDF) */}
              {exportFormat === "pdf" && (
                <button
                  onClick={handlePreviewPDF}
                  className="px-4 py-3 bg-dark-700 hover:bg-dark-600 text-white border border-dark-600 rounded-xl font-bold transition flex items-center gap-2"
                  title="Preview PDF"
                >
                  <Eye size={18} /> Preview
                </button>
              )}
              <button
                onClick={handleGenerate}
                disabled={isGenerating}
                className={`flex-1 py-3 text-black rounded-xl font-bold transition flex items-center justify-center gap-2 ${
                  isGenerating
                    ? "bg-gray-600 cursor-not-allowed"
                    : "bg-accent-cyan hover:bg-cyan-400 shadow-lg shadow-cyan-900/20"
                }`}
              >
                {isGenerating ? (
                  <>
                    <Loader2 size={18} className="animate-spin" /> Processing...
                  </>
                ) : (
                  "Download File"
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* --- MODAL KHUSUS PREVIEW PDF --- */}
      {isPreviewOpen && previewUrl && (
        <div className="fixed inset-0 bg-black/90 backdrop-blur-md z-[60] flex flex-col animate-in fade-in duration-200">
          
          {/* Header Preview */}
          <div className="flex justify-between items-center p-4 bg-dark-900 border-b border-dark-700">
            <h2 className="text-white font-bold flex items-center gap-2">
                <FileText className="text-accent-cyan" /> Preview Report
            </h2>
            <div className="flex gap-3">
                <button 
                    onClick={() => {
                        handleDownloadPDF();
                        setIsPreviewOpen(false);
                    }}
                    className="px-4 py-2 bg-accent-cyan text-black rounded-lg font-bold text-sm hover:bg-cyan-400 transition flex items-center gap-2"
                >
                    <Download size={16}/> Download Now
                </button>
                <button 
                    onClick={() => setIsPreviewOpen(false)}
                    className="p-2 bg-dark-700 text-gray-300 rounded-lg hover:bg-red-500/20 hover:text-red-500 transition"
                >
                    <X size={20} />
                </button>
            </div>
          </div>

          {/* Area Iframe PDF */}
          <div className="flex-1 w-full h-full bg-gray-800 p-4 overflow-hidden">
             <iframe 
                src={previewUrl} 
                className="w-full h-full rounded-lg border border-dark-600 shadow-2xl"
                title="PDF Preview"
             />
          </div>
        </div>
      )}
    </div>
  );
};

export default Reports;